"""Smart Money Intelligence Engine for Solbot.

Tracks wallet behavior across Pump.fun launches to identify:
- Early buyers / snipers with consistent profits
- Repeat profitable wallets (smart money)
- Repeat rug wallets (toxic money)
- Creator/deployer reputation and patterns
- Wallet clustering (coordinated buys/exits)

Provides:
- Wallet ROI, winrate, avg hold time, realized PnL
- Creator stats (launch count, rug rate, avg ATH)
- Conviction scoring (boost/penalize based on wallet overlap)
- Adaptive trust integration with scoring engine
- Copy-wallet tracking for following profitable wallets

Architecture:
- SQLite persistence for all stats
- In-memory LRU cache for hot-path lookups
- Async batch processing for scalability
- Signal-based integration with bot pipeline
"""

import asyncio
from collections import OrderedDict
from dataclasses import dataclass, field
from time import time
from typing import Optional

from solbot.logger import get_logger

logger = get_logger("smart_money")


# ── Data Models ─────────────────────────────────────────────────────────

@dataclass
class WalletStats:
    """Aggregated statistics for a tracked wallet."""
    address: str
    total_buys: int = 0
    total_sells: int = 0
    wins: int = 0
    losses: int = 0
    total_realized_pnl: float = 0.0
    avg_hold_seconds: float = 0.0
    avg_roi_pct: float = 0.0
    rug_participations: int = 0
    first_seen: float = 0.0
    last_seen: float = 0.0
    tags: list[str] = field(default_factory=list)  # "sniper", "smart_money", "rug_wallet", etc.

    @property
    def winrate(self) -> float:
        total = self.wins + self.losses
        return (self.wins / total * 100) if total > 0 else 0.0

    @property
    def rug_rate(self) -> float:
        if self.total_buys == 0:
            return 0.0
        return (self.rug_participations / self.total_buys) * 100

    @property
    def conviction_score(self) -> float:
        """0-100 score representing wallet quality/reliability."""
        if self.total_buys < 3:
            return 50.0  # Insufficient data
        score = 50.0
        # Winrate contribution (0-30)
        score += min(self.winrate * 0.3, 30.0)
        # ROI contribution (0-20)
        score += min(max(self.avg_roi_pct, 0) * 0.2, 20.0)
        # Rug penalty (-30 to 0)
        score -= min(self.rug_rate * 0.6, 30.0)
        # Volume bonus (more trades = more data = more reliable)
        if self.total_buys >= 10:
            score += 5.0
        if self.total_buys >= 25:
            score += 5.0
        return max(0.0, min(100.0, score))

    @property
    def is_smart_money(self) -> bool:
        return self.conviction_score >= 70 and self.total_buys >= 5

    @property
    def is_toxic(self) -> bool:
        return self.rug_rate >= 40 or self.conviction_score <= 25


@dataclass
class CreatorStats:
    """Aggregated statistics for a token creator/deployer."""
    address: str
    total_launches: int = 0
    successful_launches: int = 0  # Token survived > 1 hour with positive price
    rugged_launches: int = 0
    avg_ath_multiplier: float = 0.0
    avg_liquidity_at_launch: float = 0.0
    total_volume_generated: float = 0.0
    first_launch: float = 0.0
    last_launch: float = 0.0
    known_wallets: list[str] = field(default_factory=list)  # Associated wallets

    @property
    def rug_rate(self) -> float:
        if self.total_launches == 0:
            return 0.0
        return (self.rugged_launches / self.total_launches) * 100

    @property
    def success_rate(self) -> float:
        if self.total_launches == 0:
            return 0.0
        return (self.successful_launches / self.total_launches) * 100

    @property
    def reputation_score(self) -> float:
        """0-100 reputation score for the creator."""
        if self.total_launches == 0:
            return 50.0
        score = 50.0
        score += min(self.success_rate * 0.3, 30.0)
        score -= min(self.rug_rate * 0.5, 40.0)
        if self.avg_ath_multiplier >= 5.0:
            score += 10.0
        elif self.avg_ath_multiplier >= 2.0:
            score += 5.0
        return max(0.0, min(100.0, score))


@dataclass
class WalletCluster:
    """A group of wallets that frequently act together."""
    cluster_id: str
    wallets: list[str] = field(default_factory=list)
    co_buy_count: int = 0  # Times these wallets bought same token within window
    co_exit_count: int = 0  # Times these wallets sold same token within window
    avg_coordination_delay_seconds: float = 0.0
    is_suspicious: bool = False
    detected_at: float = field(default_factory=time)


@dataclass
class SmartMoneySignal:
    """A signal generated by smart money analysis."""
    mint: str
    signal_type: str  # "smart_money_buy", "toxic_overlap", "cluster_entry", "creator_rep"
    confidence_modifier: float = 0.0  # +/- adjustment to token confidence
    message: str = ""
    data: dict = field(default_factory=dict)
    timestamp: float = field(default_factory=time)


# ── LRU Cache ───────────────────────────────────────────────────────────

class LRUCache:
    """Simple LRU cache for hot-path wallet lookups."""

    def __init__(self, max_size: int = 500):
        self._cache: OrderedDict = OrderedDict()
        self._max_size = max_size

    def get(self, key: str):
        if key in self._cache:
            self._cache.move_to_end(key)
            return self._cache[key]
        return None

    def put(self, key: str, value):
        if key in self._cache:
            self._cache.move_to_end(key)
        self._cache[key] = value
        if len(self._cache) > self._max_size:
            self._cache.popitem(last=False)

    def invalidate(self, key: str):
        self._cache.pop(key, None)

    def clear(self):
        self._cache.clear()

    @property
    def size(self) -> int:
        return len(self._cache)


# ── Smart Money Engine ──────────────────────────────────────────────────

class SmartMoneyEngine:
    """Core Smart Money Intelligence engine.

    Responsibilities:
    1. Track wallet interactions with tokens (buys, sells, timing)
    2. Calculate wallet stats (ROI, winrate, hold time, rug %)
    3. Calculate creator stats (launch count, rug rate, ATH)
    4. Detect wallet clusters (coordinated trading)
    5. Generate smart money signals for scoring pipeline
    6. Manage copy-wallet list
    7. Provide adaptive trust scoring adjustments

    All operations are async-safe and use SQLite for persistence.
    """

    def __init__(self, db):
        self._db = db
        self._wallet_cache = LRUCache(max_size=1000)
        self._creator_cache = LRUCache(max_size=500)
        self._copy_wallets: set[str] = set()
        self._lock = asyncio.Lock()
        self._batch_queue: asyncio.Queue = asyncio.Queue(maxsize=1000)
        self._processor_task: Optional[asyncio.Task] = None
        self._running = False

    async def start(self):
        """Initialize the engine and start batch processor."""
        await self._ensure_tables()
        await self._load_copy_wallets()
        self._running = True
        self._processor_task = asyncio.create_task(self._batch_processor())
        logger.info(f"Smart Money engine started | copy_wallets={len(self._copy_wallets)}")

    async def stop(self):
        """Stop the batch processor and flush pending work."""
        self._running = False
        if self._processor_task:
            self._processor_task.cancel()
            try:
                await self._processor_task
            except asyncio.CancelledError:
                pass
        logger.info("Smart Money engine stopped")

    # ── Public API: Scoring Integration ─────────────────────────────────

    async def evaluate_token(self, mint: str, creator: str, early_buyers: list[str] = None) -> SmartMoneySignal:
        """Evaluate a token based on smart money overlap.

        Called by the scoring engine after a token passes basic filters.

        Args:
            mint: Token mint address.
            creator: Creator/deployer address.
            early_buyers: List of wallet addresses that bought early.

        Returns:
            SmartMoneySignal with confidence modifier.
        """
        modifier = 0.0
        messages = []

        # 1. Creator reputation
        creator_stats = await self.get_creator_stats(creator)
        if creator_stats:
            if creator_stats.rug_rate >= 50:
                modifier -= 25.0
                messages.append(f"Creator rug rate: {creator_stats.rug_rate:.0f}%")
            elif creator_stats.success_rate >= 60 and creator_stats.total_launches >= 3:
                modifier += 10.0
                messages.append(f"Creator success rate: {creator_stats.success_rate:.0f}%")

        # 2. Smart money overlap
        if early_buyers:
            smart_count = 0
            toxic_count = 0
            for wallet in early_buyers[:20]:  # Cap analysis
                stats = await self.get_wallet_stats(wallet)
                if stats:
                    if stats.is_smart_money:
                        smart_count += 1
                    elif stats.is_toxic:
                        toxic_count += 1

            if smart_count >= 3:
                modifier += 15.0
                messages.append(f"{smart_count} smart money wallets buying")
            elif smart_count >= 1:
                modifier += 5.0
                messages.append(f"{smart_count} smart money wallet(s) buying")

            if toxic_count >= 3:
                modifier -= 20.0
                messages.append(f"{toxic_count} toxic wallets detected")
            elif toxic_count >= 1:
                modifier -= 8.0
                messages.append(f"{toxic_count} toxic wallet(s) detected")

        # 3. Copy wallet match
        if early_buyers:
            copy_matches = set(early_buyers) & self._copy_wallets
            if copy_matches:
                modifier += 10.0
                messages.append(f"{len(copy_matches)} copy-wallet(s) buying")

        signal_type = "smart_money_boost" if modifier > 0 else ("toxic_overlap" if modifier < 0 else "neutral")

        return SmartMoneySignal(
            mint=mint,
            signal_type=signal_type,
            confidence_modifier=modifier,
            message=" | ".join(messages) if messages else "No smart money signal",
            data={
                "creator_rep": creator_stats.reputation_score if creator_stats else 50.0,
                "modifier": modifier,
            },
        )

    # ── Public API: Wallet Stats ────────────────────────────────────────

    async def get_wallet_stats(self, address: str) -> Optional[WalletStats]:
        """Get stats for a wallet (cached)."""
        cached = self._wallet_cache.get(address)
        if cached:
            return cached

        row = await self._db._fetch_all_async(
            "SELECT * FROM wallet_stats WHERE address=?", (address,)
        )
        if not row:
            return None

        r = row[0]
        stats = WalletStats(
            address=r["address"],
            total_buys=r.get("total_buys", 0),
            total_sells=r.get("total_sells", 0),
            wins=r.get("wins", 0),
            losses=r.get("losses", 0),
            total_realized_pnl=r.get("total_realized_pnl", 0.0),
            avg_hold_seconds=r.get("avg_hold_seconds", 0.0),
            avg_roi_pct=r.get("avg_roi_pct", 0.0),
            rug_participations=r.get("rug_participations", 0),
            first_seen=r.get("first_seen", 0.0),
            last_seen=r.get("last_seen", 0.0),
        )
        self._wallet_cache.put(address, stats)
        return stats

    async def get_creator_stats(self, address: str) -> Optional[CreatorStats]:
        """Get stats for a creator (cached)."""
        if not address:
            return None

        cached = self._creator_cache.get(address)
        if cached:
            return cached

        row = await self._db._fetch_all_async(
            "SELECT * FROM creator_stats WHERE address=?", (address,)
        )
        if not row:
            return None

        r = row[0]
        stats = CreatorStats(
            address=r["address"],
            total_launches=r.get("total_launches", 0),
            successful_launches=r.get("successful_launches", 0),
            rugged_launches=r.get("rugged_launches", 0),
            avg_ath_multiplier=r.get("avg_ath_multiplier", 0.0),
            avg_liquidity_at_launch=r.get("avg_liquidity_at_launch", 0.0),
            total_volume_generated=r.get("total_volume_generated", 0.0),
            first_launch=r.get("first_launch", 0.0),
            last_launch=r.get("last_launch", 0.0),
        )
        self._creator_cache.put(address, stats)
        return stats

    # ── Public API: Record Events ───────────────────────────────────────

    async def record_wallet_buy(self, wallet: str, mint: str, amount_sol: float, timestamp: float = 0.0):
        """Record a wallet buying a token."""
        ts = timestamp or time()
        await self._enqueue_event("wallet_buy", {
            "wallet": wallet, "mint": mint, "amount_sol": amount_sol, "timestamp": ts
        })

    async def record_wallet_sell(self, wallet: str, mint: str, amount_sol: float, pnl_sol: float, hold_seconds: float):
        """Record a wallet selling a token."""
        await self._enqueue_event("wallet_sell", {
            "wallet": wallet, "mint": mint, "amount_sol": amount_sol,
            "pnl_sol": pnl_sol, "hold_seconds": hold_seconds, "timestamp": time()
        })

    async def record_token_launch(self, mint: str, creator: str, liquidity_sol: float):
        """Record a new token launch."""
        await self._enqueue_event("token_launch", {
            "mint": mint, "creator": creator, "liquidity_sol": liquidity_sol, "timestamp": time()
        })

    async def record_rug(self, mint: str, creator: str, buyers: list[str] = None):
        """Record a rug pull event."""
        await self._enqueue_event("rug", {
            "mint": mint, "creator": creator, "buyers": buyers or [], "timestamp": time()
        })

    # ── Public API: Copy Wallets ────────────────────────────────────────

    async def add_copy_wallet(self, address: str) -> bool:
        """Add a wallet to the copy-tracking list."""
        if address in self._copy_wallets:
            return False
        self._copy_wallets.add(address)
        await self._db._fetch_all_async(
            "INSERT OR IGNORE INTO copy_wallets (address, added_at) VALUES (?, ?)",
            (address, time())
        )
        logger.info(f"Copy wallet added: {address[:16]}...")
        return True

    async def remove_copy_wallet(self, address: str) -> bool:
        """Remove a wallet from the copy-tracking list."""
        if address not in self._copy_wallets:
            return False
        self._copy_wallets.discard(address)
        await self._db._fetch_all_async(
            "DELETE FROM copy_wallets WHERE address=?", (address,)
        )
        logger.info(f"Copy wallet removed: {address[:16]}...")
        return True

    def get_copy_wallets(self) -> list[str]:
        """Get all copy-tracked wallets."""
        return list(self._copy_wallets)

    # ── Public API: Clustering ──────────────────────────────────────────

    async def detect_clusters(self, mint: str, buyers: list[str], window_seconds: float = 30.0) -> list[WalletCluster]:
        """Detect wallet clusters among buyers of a token.

        Wallets that frequently buy the same tokens within a time window
        are flagged as potentially coordinated.
        """
        if len(buyers) < 3:
            return []

        # Check historical co-buying patterns
        clusters = []
        buyer_set = set(buyers)

        for wallet in buyers[:15]:  # Limit analysis
            # Find other wallets this wallet frequently co-buys with
            co_buyers = await self._db._fetch_all_async(
                """SELECT w2.wallet, COUNT(*) as co_count
                   FROM wallet_token_interactions w1
                   JOIN wallet_token_interactions w2
                     ON w1.mint = w2.mint AND w1.wallet != w2.wallet
                   WHERE w1.wallet = ? AND w2.wallet IN ({})
                     AND ABS(w1.timestamp - w2.timestamp) < ?
                   GROUP BY w2.wallet
                   HAVING co_count >= 3
                   ORDER BY co_count DESC LIMIT 5""".format(
                    ",".join("?" * len(buyers))
                ),
                (wallet, *buyers, window_seconds),
            )

            if co_buyers and len(co_buyers) >= 2:
                cluster_wallets = [wallet] + [r["wallet"] for r in co_buyers]
                clusters.append(WalletCluster(
                    cluster_id=f"cluster_{wallet[:8]}",
                    wallets=cluster_wallets,
                    co_buy_count=sum(r["co_count"] for r in co_buyers),
                    is_suspicious=True,
                ))

        return clusters

    # ── Public API: Top Wallets ─────────────────────────────────────────

    async def get_top_wallets(self, limit: int = 10) -> list[dict]:
        """Get top-performing tracked wallets."""
        rows = await self._db._fetch_all_async(
            """SELECT address, total_buys, wins, losses, total_realized_pnl,
                      avg_roi_pct, rug_participations
               FROM wallet_stats
               WHERE total_buys >= 5
               ORDER BY total_realized_pnl DESC
               LIMIT ?""",
            (limit,),
        )
        return rows

    async def get_top_creators(self, limit: int = 10) -> list[dict]:
        """Get top-reputation creators."""
        rows = await self._db._fetch_all_async(
            """SELECT address, total_launches, successful_launches, rugged_launches,
                      avg_ath_multiplier
               FROM creator_stats
               WHERE total_launches >= 2
               ORDER BY successful_launches DESC
               LIMIT ?""",
            (limit,),
        )
        return rows

    # ── Internal: Batch Processor ───────────────────────────────────────

    async def _batch_processor(self):
        """Background task that processes queued events in batches."""
        while self._running:
            try:
                batch = []
                # Collect up to 20 events or wait 2 seconds
                try:
                    while len(batch) < 20:
                        event = await asyncio.wait_for(self._batch_queue.get(), timeout=2.0)
                        batch.append(event)
                except asyncio.TimeoutError:
                    pass

                if batch:
                    await self._process_batch(batch)

            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Batch processor error: {e}")
                await asyncio.sleep(1.0)

    async def _process_batch(self, batch: list[dict]):
        """Process a batch of events."""
        for event in batch:
            event_type = event.get("type")
            data = event.get("data", {})

            try:
                if event_type == "wallet_buy":
                    await self._process_wallet_buy(data)
                elif event_type == "wallet_sell":
                    await self._process_wallet_sell(data)
                elif event_type == "token_launch":
                    await self._process_token_launch(data)
                elif event_type == "rug":
                    await self._process_rug(data)
            except Exception as e:
                logger.error(f"Event processing error ({event_type}): {e}")

    async def _process_wallet_buy(self, data: dict):
        """Update wallet stats on buy."""
        wallet = data["wallet"]
        mint = data["mint"]
        ts = data["timestamp"]

        await self._db._fetch_all_async(
            """INSERT INTO wallet_token_interactions (wallet, mint, side, amount_sol, timestamp)
               VALUES (?, ?, 'buy', ?, ?)""",
            (wallet, mint, data["amount_sol"], ts),
        )

        await self._db._fetch_all_async(
            """INSERT INTO wallet_stats (address, total_buys, first_seen, last_seen)
               VALUES (?, 1, ?, ?)
               ON CONFLICT(address) DO UPDATE SET
                 total_buys = total_buys + 1,
                 last_seen = ?""",
            (wallet, ts, ts, ts),
        )
        self._wallet_cache.invalidate(wallet)

    async def _process_wallet_sell(self, data: dict):
        """Update wallet stats on sell."""
        wallet = data["wallet"]
        pnl = data["pnl_sol"]
        hold = data["hold_seconds"]

        win = 1 if pnl > 0 else 0
        loss = 1 if pnl <= 0 else 0

        await self._db._fetch_all_async(
            """INSERT INTO wallet_token_interactions (wallet, mint, side, amount_sol, pnl_sol, hold_seconds, timestamp)
               VALUES (?, ?, 'sell', ?, ?, ?, ?)""",
            (wallet, data["mint"], data["amount_sol"], pnl, hold, data["timestamp"]),
        )

        await self._db._fetch_all_async(
            """UPDATE wallet_stats SET
                 total_sells = total_sells + 1,
                 wins = wins + ?,
                 losses = losses + ?,
                 total_realized_pnl = total_realized_pnl + ?,
                 last_seen = ?
               WHERE address = ?""",
            (win, loss, pnl, data["timestamp"], wallet),
        )
        self._wallet_cache.invalidate(wallet)

    async def _process_token_launch(self, data: dict):
        """Record a token launch in creator stats."""
        creator = data["creator"]
        ts = data["timestamp"]

        await self._db._fetch_all_async(
            """INSERT INTO token_lifecycle (mint, creator, launched_at, initial_liquidity_sol)
               VALUES (?, ?, ?, ?)""",
            (data["mint"], creator, ts, data["liquidity_sol"]),
        )

        await self._db._fetch_all_async(
            """INSERT INTO creator_stats (address, total_launches, first_launch, last_launch)
               VALUES (?, 1, ?, ?)
               ON CONFLICT(address) DO UPDATE SET
                 total_launches = total_launches + 1,
                 last_launch = ?""",
            (creator, ts, ts, ts),
        )
        self._creator_cache.invalidate(creator)

    async def _process_rug(self, data: dict):
        """Process a rug pull event."""
        creator = data["creator"]
        buyers = data["buyers"]

        # Update creator rug count
        await self._db._fetch_all_async(
            "UPDATE creator_stats SET rugged_launches = rugged_launches + 1 WHERE address = ?",
            (creator,),
        )
        self._creator_cache.invalidate(creator)

        # Update buyer rug participation counts
        for wallet in buyers[:50]:
            await self._db._fetch_all_async(
                "UPDATE wallet_stats SET rug_participations = rug_participations + 1 WHERE address = ?",
                (wallet,),
            )
            self._wallet_cache.invalidate(wallet)

    # ── Internal: Event Queue ───────────────────────────────────────────

    async def _enqueue_event(self, event_type: str, data: dict):
        """Add an event to the batch processing queue."""
        try:
            self._batch_queue.put_nowait({"type": event_type, "data": data})
        except asyncio.QueueFull:
            logger.warning("Smart money event queue full, dropping event")

    # ── Internal: Database Setup ────────────────────────────────────────

    async def _ensure_tables(self):
        """Create smart money tables if they don't exist."""
        await self._db._fetch_all_async("""
            CREATE TABLE IF NOT EXISTS wallet_stats (
                address TEXT PRIMARY KEY,
                total_buys INTEGER DEFAULT 0,
                total_sells INTEGER DEFAULT 0,
                wins INTEGER DEFAULT 0,
                losses INTEGER DEFAULT 0,
                total_realized_pnl REAL DEFAULT 0.0,
                avg_hold_seconds REAL DEFAULT 0.0,
                avg_roi_pct REAL DEFAULT 0.0,
                rug_participations INTEGER DEFAULT 0,
                first_seen REAL DEFAULT 0.0,
                last_seen REAL DEFAULT 0.0
            )
        """)

        await self._db._fetch_all_async("""
            CREATE TABLE IF NOT EXISTS creator_stats (
                address TEXT PRIMARY KEY,
                total_launches INTEGER DEFAULT 0,
                successful_launches INTEGER DEFAULT 0,
                rugged_launches INTEGER DEFAULT 0,
                avg_ath_multiplier REAL DEFAULT 0.0,
                avg_liquidity_at_launch REAL DEFAULT 0.0,
                total_volume_generated REAL DEFAULT 0.0,
                first_launch REAL DEFAULT 0.0,
                last_launch REAL DEFAULT 0.0
            )
        """)

        await self._db._fetch_all_async("""
            CREATE TABLE IF NOT EXISTS token_lifecycle (
                mint TEXT PRIMARY KEY,
                creator TEXT NOT NULL,
                launched_at REAL NOT NULL,
                initial_liquidity_sol REAL DEFAULT 0.0,
                peak_mcap_usd REAL DEFAULT 0.0,
                ath_multiplier REAL DEFAULT 0.0,
                is_rugged INTEGER DEFAULT 0,
                rugged_at REAL DEFAULT 0.0
            )
        """)

        await self._db._fetch_all_async("""
            CREATE TABLE IF NOT EXISTS wallet_token_interactions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                wallet TEXT NOT NULL,
                mint TEXT NOT NULL,
                side TEXT NOT NULL,
                amount_sol REAL DEFAULT 0.0,
                pnl_sol REAL DEFAULT 0.0,
                hold_seconds REAL DEFAULT 0.0,
                timestamp REAL NOT NULL
            )
        """)

        await self._db._fetch_all_async("""
            CREATE TABLE IF NOT EXISTS copy_wallets (
                address TEXT PRIMARY KEY,
                added_at REAL NOT NULL
            )
        """)

        await self._db._fetch_all_async(
            "CREATE INDEX IF NOT EXISTS idx_wti_wallet ON wallet_token_interactions(wallet)"
        )
        await self._db._fetch_all_async(
            "CREATE INDEX IF NOT EXISTS idx_wti_mint ON wallet_token_interactions(mint)"
        )
        await self._db._fetch_all_async(
            "CREATE INDEX IF NOT EXISTS idx_wti_timestamp ON wallet_token_interactions(timestamp)"
        )

        logger.info("Smart money tables initialized")

    async def _load_copy_wallets(self):
        """Load copy wallet list from database."""
        rows = await self._db._fetch_all_async("SELECT address FROM copy_wallets")
        self._copy_wallets = {r["address"] for r in rows}
